# Generated by Django 6.0.4 on 2026-04-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proximo_control', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Graduado', 'Graduado'), ('Abandono', 'Abandono')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninos.nino')),
            ],
        ),
    ]
